# ============================================================================ #
# Copyright (c) 2026 NVIDIA Corporation & Affiliates.                          #
# All rights reserved.                                                         #
#                                                                              #
# This source code and the accompanying materials are made available under     #
# the terms of the Apache License 2.0 which accompanies this distribution.     #
# ============================================================================ #

################################################################################
# Define the shared core library libcudaqMLIR.so
#
# It bundles the following compilation units into one shared library:
#  - All the object files of the libraries registered via register_cudaq_mlir_lib
#  - All the MLIR libraries listed in mlir-libs-allowlist.txt
#
# MLIR libraries are linked as WHOLE_ARCHIVE so their full symbol set is
# exported for downstream plugins.
################################################################################

# cudaq_read_symbol_list() comes from cmake/modules/AddCUDAQ.cmake, which the
# top-level CMakeLists.txt includes before add_subdirectory(cudaq).
set(LIBRARY_NAME cudaqMLIR)
get_property(_cudaq_bundle_libs GLOBAL PROPERTY CUDAQ_MLIR_BUNDLE_LIBS)

# 1. Bundle the list of all MLIR object files. This assumes that every bundled
# lib was built with ENABLE_AGGREGATION (e.g. via add_cudaq_library)
set(_cudaq_bundle_objs)
foreach(_lib IN LISTS _cudaq_bundle_libs)
  if(TARGET obj.${_lib})
    list(APPEND _cudaq_bundle_objs "$<TARGET_OBJECTS:obj.${_lib}>")
    # Do not export inline/template member functions, as downstream re-emits
    # them from headers anyway.
    target_compile_options(obj.${_lib} PRIVATE
      "$<$<COMPILE_LANGUAGE:CXX>:-fvisibility-inlines-hidden>"
      -ffunction-sections -fdata-sections)
  else()
    message(WARNING
      "${LIBRARY_NAME}: obj.${_lib} not found; ensure ${_lib} is built with ENABLE_AGGREGATION")
  endif()
endforeach()
add_library(${LIBRARY_NAME} SHARED ${_cudaq_bundle_objs})

# Provide the namespaced alias cudaq::cudaqMLIR used downstream
add_library(cudaq::${LIBRARY_NAME} ALIAS ${LIBRARY_NAME})

# 2. Pull in the dependencies
target_link_libraries(${LIBRARY_NAME} PRIVATE ${_cudaq_bundle_libs})

# 3. WHOLE_ARCHIVE the allowlisted MLIR libraries, the C-API dependencies and
# the LLVM components needed for JITing so their full symbol set is exported for
# downstream plugins.
#
# All three sources feed a single list: whole-archiving the same archive twice
# would define every one of its symbols twice and fail the link.
cudaq_read_symbol_list(
  "${CMAKE_CURRENT_SOURCE_DIR}/mlir-libs-allowlist.txt" _cudaq_mlir_whole_archive)

# Recorded in cudaq/lib/Optimizer/CAPI/CMakeLists.txt: everything the embedded
# Python C-API object files were built against.
get_property(_cudaq_required_mlir_libs GLOBAL PROPERTY CUDAQ_MLIR_REQUIRED_LIBS)
list(APPEND _cudaq_mlir_whole_archive ${_cudaq_required_mlir_libs})

llvm_map_components_to_libnames(_cudaq_llvm_native_libs native nativecodegen)
list(APPEND _cudaq_mlir_whole_archive ${_cudaq_llvm_native_libs})

list(REMOVE_DUPLICATES _cudaq_mlir_whole_archive)

# Publish what the library ends up containing. This is the contract downstream
# projects build against: AddCUDAQ.cmake reads it to decide which static MLIR
# archives a downstream C-API library must *not* link, because libcudaqMLIR
# already provides them. Written at configure time (not file(GENERATE)) so that
# python/ can read it later in this same configure run.
set(CUDAQ_MLIR_CONTENTS_FILE
  "${CMAKE_BINARY_DIR}/lib/cmake/cudaq/cudaqMLIR-contents.txt")
list(JOIN _cudaq_mlir_whole_archive "\n" _cudaq_mlir_contents)
file(WRITE "${CUDAQ_MLIR_CONTENTS_FILE}"
  "# Generated by cudaqMLIR-shlib.cmake -- do not edit.\n"
  "# MLIR/LLVM libraries whole-archived into libcudaqMLIR, i.e. the set a\n"
  "# downstream project must resolve dynamically rather than link statically.\n"
  "${_cudaq_mlir_contents}\n")
install(FILES "${CUDAQ_MLIR_CONTENTS_FILE}"
        DESTINATION lib/cmake/cudaq
        COMPONENT Development)

foreach(_lib IN LISTS _cudaq_mlir_whole_archive)
  if(TARGET ${_lib})
    target_link_libraries(${LIBRARY_NAME} PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,${_lib}>")
  else()
    message(WARNING
      "${LIBRARY_NAME}: MLIR library '${_lib}' not found; skipping whole-archive")
  endif()
endforeach()

# Ideally, we use -Bsymbolic-functions as it removes PLT/GOT indirection. However
# that also opts the library out of ELF symbol interposition, which we currently
# rely on to deduplicate symbols when libstdc++/libgcc are statically linked into
# multiple CUDA-Q shared objects (otherwise exception unwinding breaks).
if(NOT APPLE AND NOT CUDAQ_STATIC_CXX_RUNTIME)
  target_link_options(${LIBRARY_NAME} PRIVATE "LINKER:-Bsymbolic-functions")
endif()

# Garbage-collect functions/data not reachable from exported symbols.
if(APPLE)
  target_link_options(${LIBRARY_NAME} PRIVATE "LINKER:-dead_strip")
else()
  target_link_options(${LIBRARY_NAME} PRIVATE "LINKER:--gc-sections")
endif()

install(TARGETS ${LIBRARY_NAME}
        EXPORT cudaq-targets
        DESTINATION lib
        COMPONENT Runtime)
set_target_properties(${LIBRARY_NAME} PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
