#!/usr/bin/env python3

import sys

from auditwheel.main import main
from auditwheel.policy import _POLICIES as POLICIES

# Do not include the OpenMP lib required by nvqir-qpp
libs = ["libgomp.so.1"]

for p in POLICIES:
    p['lib_whitelist'].extend(libs)

if __name__ == "__main__":
    sys.exit(main())