# ============================================================================ #
# Copyright (c) 2026 NVIDIA Corporation & Affiliates.                          #
# All rights reserved.                                                         #
#                                                                              #
# This source code and the accompanying materials are made available under     #
# the terms of the Apache License 2.0 which accompanies this distribution.     #
# ============================================================================ #
"""Seeded generators for straight-line, bounded-unitary Quake inputs.

Corpora are reproducible: the same generator version, seed, and parameters always
produce byte-identical Quake IR. Every generated module is stamped with its
provenance so a failing case can be regenerated from the result alone, and seeds
come only from the pinned seed sets here (never from anything the optimizer
controls). Bump :data:`CORPUS_GENERATOR_VERSION` whenever a change to the
generation logic alters its output.
"""

import random
from pathlib import Path

# Bump on any change to generation that alters the emitted IR. Stamped into every
# generated module so a corpus's provenance is unambiguous.
CORPUS_GENERATOR_VERSION = 1

# Non-parametric single-qubit gates used as filler.
_SINGLE = ("h", "x", "y", "z", "s", "t")
# Involutions: g applied twice is the identity (up to nothing for these).
_INVOLUTIONS = ("h", "x", "y", "z")

_BASE_SEED = 184467
_PRESET_SIZES = {
    "single-reproducer": 1,
    "smoke": 3,
    "quick": 8,
    "ci": 24,
    "full": 64,
}
CORPUS_SEED_SETS = {
    preset: tuple(_BASE_SEED + i for i in range(size))
    for preset, size in _PRESET_SIZES.items()
}


def seeds_for_preset(preset: str) -> tuple:
    """Return the pinned seed tuple for ``preset``.

    Raises ``ValueError`` for an unknown preset so a typo can never silently
    yield an empty corpus.
    """
    try:
        return CORPUS_SEED_SETS[preset]
    except KeyError:
        raise ValueError(f"unknown corpus preset '{preset}'; "
                         f"known: {sorted(CORPUS_SEED_SETS)}")


def _provenance_header(seed: int, num_qubits: int, length: int) -> list:
    """Comment lines identifying how a generated module was produced."""
    return [
        f"// Generated by cudaq._compiler.optimization_corpus "
        f"v{CORPUS_GENERATOR_VERSION}",
        f"// seed={seed} num_qubits={num_qubits} length={length}",
    ]


def generate_module_text(seed: int,
                         num_qubits: int = 2,
                         length: int = 6,
                         kernel_name: str = "kern") -> str:
    """Return the Quake IR text for one seeded straight-line kernel.

    The text is prefixed with a provenance header (generator version + seed +
    parameters) as MLIR line comments, so a generated file is self-identifying
    and reproducible from that header alone.
    """
    rng = random.Random(seed)
    n = max(1, num_qubits)

    lines = _provenance_header(seed, num_qubits, length)
    lines.append(f"func.func @{kernel_name}() {{")
    lines.append("  %cst = arith.constant 1.000000e+00 : f64")
    lines.append(f"  %q = quake.alloca !quake.veq<{n}>")
    refs = []
    for i in range(n):
        lines.append(f"  %r{i} = quake.extract_ref %q[{i}] : "
                     f"(!quake.veq<{n}>) -> !quake.ref")
        refs.append(f"%r{i}")

    for _ in range(length):
        choice = rng.random()
        target = rng.randrange(n)
        if choice < 0.6:
            gate = rng.choice(_SINGLE)
            lines.append(f"  quake.{gate} {refs[target]} : (!quake.ref) -> ()")
        elif choice < 0.8 or n < 2:
            lines.append(f"  quake.rz (%cst) {refs[target]} : "
                         f"(f64, !quake.ref) -> ()")
        else:
            control = rng.randrange(n)
            while control == target:
                control = rng.randrange(n)
            lines.append(f"  quake.x [{refs[control]}] {refs[target]} : "
                         f"(!quake.ref, !quake.ref) -> ()")

    # Injected motifs: a self-inverse pair and a pair of `mergeable` rotations.
    motif_target = rng.randrange(n)
    involution = rng.choice(_INVOLUTIONS)
    lines.append(f"  quake.{involution} {refs[motif_target]} : "
                 f"(!quake.ref) -> ()")
    lines.append(f"  quake.{involution} {refs[motif_target]} : "
                 f"(!quake.ref) -> ()")
    lines.append(f"  quake.rz (%cst) {refs[motif_target]} : "
                 f"(f64, !quake.ref) -> ()")
    lines.append(f"  quake.rz (%cst) {refs[motif_target]} : "
                 f"(f64, !quake.ref) -> ()")

    lines.append("  cc.return")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_corpus(directory,
                 seeds,
                 num_qubits: int = 2,
                 length: int = 6) -> list:
    """Write one ``generated_<seed>.qke`` per seed into ``directory``.

    Returns the list of written paths. Reproducible: same seeds and parameters
    always produce byte-identical files.
    """
    out = Path(directory)
    out.mkdir(parents=True, exist_ok=True)
    paths = []
    for seed in seeds:
        text = generate_module_text(seed, num_qubits, length)
        path = out / f"generated_{seed}.qke"
        path.write_text(text)
        paths.append(path)
    return paths


def corpus_for_preset(directory,
                      preset: str,
                      num_qubits: int = 2,
                      length: int = 6) -> list:
    """Materialize the pinned corpus for ``preset`` into ``directory``.

    Depth knob over the seed sets: ``smoke`` < ``quick`` < ``ci`` < ``full``,
    plus a one-input ``single-reproducer``. Reproducible for a given generator
    version and parameters.
    """
    return write_corpus(directory, seeds_for_preset(preset), num_qubits, length)
