coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: pr
        informational: true
    patch:
      default:
        informational: true
ignore:
   - "tpls"
fixes:
   - "/workspaces/cuda-quantum::"