# General LLVM build settings
set(LLVM_TARGETS_TO_BUILD host CACHE STRING "")
set(LLVM_ENABLE_BINDINGS OFF CACHE BOOL "")
set(LLVM_OPTIMIZED_TABLEGEN ON CACHE BOOL "")
set(LLVM_INSTALL_UTILS ON CACHE BOOL "")
set(ZLIB_USE_STATIC_LIBS ON CACHE BOOL "")
set(LLVM_ENABLE_ZSTD OFF CACHE BOOL "")

# Path configurations
set(CMAKE_INSTALL_RPATH "$ORIGIN:$ORIGIN/lib:$ORIGIN/../lib" CACHE STRING "")
#set(LIBCXX_INSTALL_LIBRARY_DIR lib CACHE STRING "" FORCE)
#set(LIBCXX_INSTALL_INCLUDE_DIR ...)
set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR ON CACHE BOOL "")

# Default configurations for the built toolchain
set(CLANG_DEFAULT_OPENMP_RUNTIME libomp CACHE STRING "")
set(CLANG_DEFAULT_LINKER lld CACHE STRING "")
set(CLANG_DEFAULT_CXX_STDLIB libc++ CACHE STRING "")
#if not runtimes contains llvm-libgcc:
set(CLANG_DEFAULT_RTLIB compiler-rt CACHE STRING "")
set(CLANG_DEFAULT_UNWINDLIB libunwind CACHE STRING "")

# Runtime related build configurations
set(LLVM_ENABLE_LIBCXX ON CACHE BOOL "")
set(LIBCXX_CXX_ABI libcxxabi CACHE STRING "")
#if runtimes contains llvm-libgcc:
# ... does not work ...
#set(LLVM_LIBGCC_EXPLICIT_OPT_IN ON CACHE BOOL "")
set(COMPILER_RT_USE_LIBCXX ON CACHE BOOL "")
set(COMPILER_RT_USE_LLVM_UNWINDER ON CACHE BOOL "")
set(LIBUNWIND_USE_COMPILER_RT ON CACHE BOOL "")
set(LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")
set(LIBCXXABI_USE_COMPILER_RT ON CACHE BOOL "")
set(LIBCXXABI_USE_LLVM_UNWINDER ON CACHE BOOL "")
set(LIBUNWIND_HAS_GCC_LIB OFF CACHE BOOL "")
set(LIBUNWIND_HAS_GCC_S_LIB OFF CACHE BOOL "")
set(LIBCXXABI_HAS_GCC_LIB OFF CACHE BOOL "")
set(LIBCXXABI_HAS_GCC_S_LIB OFF CACHE BOOL "")
set(LIBCXX_HAS_GCC_LIB OFF CACHE BOOL "")
set(LIBCXX_HAS_GCC_S_LIB OFF CACHE BOOL "")
set(LIBCXX_HAS_ATOMIC_LIB OFF CACHE BOOL "")
set(COMPILER_RT_HAS_GCC_LIB OFF CACHE BOOL "")
set(COMPILER_RT_HAS_GCC_S_LIB OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_CRT ON CACHE BOOL "")
set(COMPILER_RT_BUILD_BUILTINS ON CACHE BOOL "")
set(COMPILER_RT_USE_BUILTINS_LIBRARY ON CACHE BOOL "")

# COMPILER_RT_BUILD_STANDALONE_LIBATOMIC? - check if these need to be set:
#set(COMPILER_RT_HAS_ATOMICS OFF CACHE BOOL "")
#set(LLVM_HAS_ATOMICS OFF CACHE BOOL "")

# Build a static libc++ without any dependencies;
# see also https://libcxx.llvm.org/BuildingLibcxx.html
set(LIBCXX_HERMETIC_STATIC_LIBRARY ON CACHE BOOL "")
set(LIBCXXABI_HERMETIC_STATIC_LIBRARY ON CACHE BOOL "")
set(LIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY ON CACHE BOOL "")
set(LIBCXXABI_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
set(LIBCXXABI_STATICALLY_LINK_UNWINDER_IN_STATIC_LIBRARY ON CACHE BOOL "")
set(COMPILER_RT_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
#set(COMPILER_RT_BUILTINS_HIDE_SYMBOLS ON CACHE BOOL "")

# If we want to build dynamic libraries for the unwinder,
# we need to build support for exception handling.
set(LLVM_ENABLE_EH ON CACHE BOOL "")
set(LLVM_ENABLE_RTTI ON CACHE BOOL "")

# See also the multi-stage LLVM build: 
# https://github.com/llvm/llvm-project/blob/main/clang/cmake/caches/Release.cmake