header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: NVIDIA Corporation & Affiliates
    software-name: CUDA Quantum

    content: |
      Copyright (c) 2023 NVIDIA Corporation & Affiliates.
      All rights reserved.

      This source code and the accompanying materials are made available under
      the terms of the Apache License 2.0 which accompanies this distribution.

    pattern: |
      Apache License 2.0

  paths:
    - '**'

  paths-ignore:
    - '**/*.md'
    - '**/*.rst'
    - '**/*.patch'
    - '**/*.config'
    - '**/.*'
    - '**/.*/**'
    - '**/Doxyfile.in'
    - 'docs/sphinx/examples'
    - 'CITATION.cff'
    - 'LICENSE'
    - 'NOTICE'
    - 'build'
    - 'examples'
    - 'tpls'
    - 'docs/sphinx/_templates'
    - 'runtime/cudaq/algorithms/optimizers/nlopt/nlopt-src'

  comment: on-failure

  license-location-threshold: 80
