header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: NVIDIA Corporation & Affiliates
    software-name: CUDA-Q

    content: |
      Copyright (c) 2023 - 2026 NVIDIA Corporation & Affiliates.
      All rights reserved.

      This source code and the accompanying materials are made available under
      the terms of the Apache License 2.0 which accompanies this distribution.

    pattern: |
      Apache License 2.0

  paths:
    - '**'

  paths-ignore:
    - '**/*.md'
    - '**/*.rst'
    - '**/*.patch'
    - '**/*.config'
    - '**/.*'
    - '**/.*/**'
    - '**/Doxyfile.in'
    - 'CITATION.cff'
    - 'LICENSE'
    - 'NOTICE'
    - 'build'
    - 'examples'
    - 'tpls'
    - 'docs/sphinx/**/*.html'
    - 'docs/sphinx/applications'
    - 'docs/sphinx/examples'
    - 'docs/sphinx/targets'
    - 'docs/sphinx/_templates'
    - 'docs/sphinx/_static/cuda_quantum_icon.svg'
    - 'docker/test/installer/mpi_cuda_check.cpp'
    - 'include/cudaq/Optimizer/CodeGen/OptUtils.h'
    - 'lib/Optimizer/CodeGen/OptUtils.cpp'
    - 'runtime/cudaq/algorithms/optimizers/nlopt/nlopt-src'
    - 'python/metapackages/MANIFEST.in'

  comment: on-failure

  license-location-threshold: 80
