# ============================================================================ #
# Copyright (c) 2026 NVIDIA Corporation & Affiliates.                          #
# All rights reserved.                                                         #
#                                                                              #
# This source code and the accompanying materials are made available under     #
# the terms of the Apache License 2.0 which accompanies this distribution.     #
# ============================================================================ #
"""The standard QEC implementation library, organized by code family.

Submodules (``cudaq.logical.qec.surface``, ``cudaq.logical.qec.steane``,
``cudaq.logical.qec.magic``, ``cudaq.logical.qec.qldpc``,
``cudaq.logical.qec.reichardt``, ...) are curated views over the
by-kind canonical libraries (:mod:`cudaq.logical.codes`,
:mod:`cudaq.logical.gadgets`,
:mod:`cudaq.logical.protocols`, and
:mod:`cudaq.logical.qec.lattice_surgery`).
Fixed libraries can be linked by importing their submodule into a program or
device module. Parameterized libraries such as ``surface[d]`` return ordinary
definition sets whose offered fields are bound at module scope. There is no
registry; unbound definitions are invisible to selection.

This package also hosts the typed QEC resource-flow objectives used directly by
gadget and protocol authors (``cudaq.logical.qec.subsystem_fragment``).
"""

from cudaq.logical.qec.lowering import (
    ActionSiteHandle,
    GeneratedQECArtifact,
    QECCompiler,
    QECCompilerContext,
    QECLowering,
    QECNetworkCompiler,
    QECNetworkContext,
    qec_lowering,
)
from cudaq.logical.codes.bb import (
    BBPermutationMap,
    BBSyndromeMoment,
    BBSyndromeSchedule,
    BinaryPolynomial,
    BivariateBicycleCode,
    CyclicProduct,
    binary_polynomial,
)
from cudaq.logical.codes import (
    Block,
    CSSBlock,
    CSSCode,
    CarrierRoleMap,
    Code,
    CodeProfile,
    Concatenated,
    Distance,
    DistanceScope,
    Encoding,
    EncodingEpoch,
    EncodingEpochSchema,
    EncodingHierarchy,
    EncodingProjection,
    FixedPort,
    GaugeMeasurementMap,
    MeasurementPhase,
    MetaChecks,
    ParameterizedCode,
    PatchTransform,
    QECActionSelection,
    QECBlockBinding,
    QECBlockOwner,
    QECBlockRequest,
    QECSelectionWitness,
    RecordLogicalMap,
    Schedule,
    StabilizerCode,
    SubsystemCode,
    code,
    expose,
    fix,
    gauge,
    qec_block,
)
from cudaq.logical.gadgets import (
    BlockEndpoint,
    BlockFlow,
    CommitPoint,
    CommitPointKind,
    EndpointCollection,
    GadgetDefinition,
    GadgetInterface,
    GadgetProfile,
    GadgetSpec,
    OutcomeRole,
    OutcomeMap,
    OutcomeSyndromeTerm,
    ParameterMap,
    Port,
    ProfileBinding,
    ProfileGraph,
    ProfileParity,
    ProfileVectorExpr,
    RecordFamily,
    RecordParity,
    RecordRef,
    RecordVectorParity,
    RetryExhaustion,
    RetryPolicy,
    SuccessPredicate,
    SyndromeBundleRef,
    before_output,
    before_resource_output,
    gadget,
)
from cudaq.logical.algebra.gf2 import GF2Matrix
from cudaq.logical.protocols.definition import (
    ProtocolDefinition,
    protocol,
)
from cudaq.logical.programs.selection import (
    SelectionIntent,
    abort_on,
    condition_results,
    require,
)
from cudaq.logical.qec.objectives import (
    SubsystemFragmentObjective,
    subsystem_fragment,
)

__all__ = [
    "Block",
    "CarrierRoleMap",
    "CSSBlock",
    "CSSCode",
    "Code",
    "CodeProfile",
    "Concatenated",
    "BinaryPolynomial",
    "BBPermutationMap",
    "BBSyndromeMoment",
    "BBSyndromeSchedule",
    "BivariateBicycleCode",
    "CyclicProduct",
    "Distance",
    "DistanceScope",
    "binary_polynomial",
    "Encoding",
    "EncodingEpoch",
    "EncodingEpochSchema",
    "EncodingHierarchy",
    "EncodingProjection",
    "PatchTransform",
    "QECActionSelection",
    "QECBlockBinding",
    "QECBlockOwner",
    "QECBlockRequest",
    "QECSelectionWitness",
    "FixedPort",
    "GF2Matrix",
    "GaugeMeasurementMap",
    "MeasurementPhase",
    "MetaChecks",
    "OutcomeRole",
    "BlockEndpoint",
    "BlockFlow",
    "EndpointCollection",
    "GadgetDefinition",
    "GadgetInterface",
    "GadgetProfile",
    "GadgetSpec",
    "OutcomeMap",
    "OutcomeSyndromeTerm",
    "ParameterMap",
    "Port",
    "ProfileBinding",
    "ProfileGraph",
    "ProfileParity",
    "ProfileVectorExpr",
    "CommitPoint",
    "CommitPointKind",
    "RetryExhaustion",
    "RetryPolicy",
    "ParameterizedCode",
    "ProtocolDefinition",
    "RecordParity",
    "RecordRef",
    "RecordVectorParity",
    "RecordLogicalMap",
    "RecordFamily",
    "SelectionIntent",
    "Schedule",
    "StabilizerCode",
    "SubsystemCode",
    "SyndromeBundleRef",
    "SubsystemFragmentObjective",
    "SuccessPredicate",
    "abort_on",
    "before_output",
    "before_resource_output",
    "code",
    "condition_results",
    "qec_block",
    "require",
    "gadget",
    "gauge",
    "expose",
    "fix",
    "protocol",
    "GeneratedQECArtifact",
    "QECCompiler",
    "QECNetworkCompiler",
    "QECNetworkContext",
    "QECLowering",
    "ActionSiteHandle",
    "QECCompilerContext",
    "qec_lowering",
    "subsystem_fragment",
]
