/*******************************************************************************
 * Copyright (c) 2022 - 2026 NVIDIA Corporation & Affiliates.                  *
 * All rights reserved.                                                        *
 *                                                                             *
 * This source code and the accompanying materials are made available under    *
 * the terms of the Apache License 2.0 which accompanies this distribution.    *
 ******************************************************************************/

// Regression test for https://github.com/NVIDIA/cuda-quantum/issues/2220.
// The C++ ABI wrapper for a templated struct kernel must not appear as an
// empty gate definition in the OpenQASM 2 output.

// clang-format off
// RUN: cudaq-quake %s | cudaq-opt --pass-pipeline="builtin.module(canonicalize,lambda-lifting,apply-op-specialization,func.func(memtoreg{quantum=0}),cc-loop-normalize,cc-loop-unroll)" | cudaq-translate --convert-to=openqasm2 | FileCheck %s
// clang-format on

#include <cudaq.h>

template <std::size_t N>
struct ghz {
  void operator()() __qpu__ {
    cudaq::qvector q(N);
    h(q[0]);
    for (int i = 0; i < static_cast<int>(N) - 1; i++)
      x<cudaq::ctrl>(q[i], q[i + 1]);
    mz(q);
  }
};

int main() {
  auto counts = cudaq::sample(ghz<3>{});
  counts.dump();
}

// CHECK:  // Code generated by NVIDIA's nvq++ compiler
// CHECK:  OPENQASM 2.0;

// CHECK:  include "qelib1.inc";

// CHECK-NOT: gate {{.*}}ghz{{.*}} {
// CHECK-NOT: }

// CHECK:  qreg var0[3];
// CHECK:  h var0[0];
// CHECK:  cx var0[0], var0[1];
// CHECK:  cx var0[1], var0[2];
// CHECK:  creg var4[3];
// CHECK:  measure var0 -> var4;
