name: run-in-docker

inputs:
  image:
    required: true
  run:
    required: true
  shell:
    default: "bash"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        docker run -i ${{ inputs.image }} ${{ inputs.shell }} -s << 'EOF'
        ${{ inputs.run }}
        echo "BMH MADE IT TO THE END (inside run-in-docker)"
        EOF
