name: run-in-docker

inputs:
  image:
    required: true
  run:
    required: true
  user:
    default: "root"
    required: false
  shell:
    default: "bash"
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Note: "bash -s << EOF" does not play nice with mpirun/mpiexec. It
        # silently skips any shell commands that come after the mpirun/mpiexec,
        # so don't use it. Use this instead, which seems to work better.
        tmpFile=$(mktemp)
        cat > $tmpFile << 'EOF'
        ${{ inputs.run }}
        EOF
        container=$(docker run --user ${{ inputs.user }} -id ${{ inputs.image }})
        docker cp $tmpFile $container:$tmpFile
        docker exec -it --user root $container chown -R ${{ inputs.user }}:${{ inputs.user }} $tmpFile
        docker exec $container ${{ inputs.shell }} $tmpFile
        docker stop $container
        rm $tmpFile
