/****************************************************************-*- C++ -*-****
 * Copyright (c) 2022 - 2025 NVIDIA Corporation & Affiliates.                  *
 * All rights reserved.                                                        *
 *                                                                             *
 * This source code and the accompanying materials are made available under    *
 * the terms of the Apache License 2.0 which accompanies this distribution.    *
 ******************************************************************************/

#pragma once

#include "cudaq/Optimizer/Dialect/CC/CCOps.h"
#include "cudaq/Optimizer/Dialect/CC/CCTypes.h"
#include "cudaq/qis/state.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Types.h"
#include <list>
#include <unordered_set>
#include <vector>

namespace cudaq::opt {

class ArgumentConverter {
public:
  /// Build an instance to create argument substitutions for a specified \p
  /// kernelName in \p sourceModule.
  ArgumentConverter(mlir::StringRef kernelName, mlir::ModuleOp sourceModule);

  /// Generate a substitution ModuleOp for the vector of arguments presented.
  /// The arguments are those presented to the kernel, kernelName.
  void gen(const std::vector<void *> &arguments);

  /// Generate a substitution ModuleOp but include only the arguments that do
  /// not appear in the set of \p exclusions.
  void gen(const std::vector<void *> &arguments,
           const std::unordered_set<unsigned> &exclusions);

  /// Generate a substitution ModuleOp but drop the first \p numDrop arguments
  /// and thereby exclude them from the substitutions.
  void gen_drop_front(const std::vector<void *> &arguments, unsigned numDrop);

  /// Get the list of substitutions that were generated by `gen()`.
  mlir::SmallVector<cudaq::cc::ArgumentSubstitutionOp> &getSubstitutions() {
    return substitutions;
  }

  /// Some substitutions may generate global constant information. Use this
  /// interface to access both the substitutions and any global constants
  /// created.
  mlir::ModuleOp getSubstitutionModule() { return substModule; }

  mlir::ModuleOp getSourceModule() { return sourceModule; }

  mlir::StringRef getKernelName() { return kernelName; }

  void genCallee(mlir::StringRef calleeName, std::vector<void *> &args) {
    auto &converter = calleeConverters.emplace_back(calleeName, substModule);
    converter.gen(args);
  }

  std::vector<ArgumentConverter> &getCalleeConverters() {
    return calleeConverters;
  }

  static bool isRegisteredKernelName(const std::string &kernelName) {
    return std::find(kernelNameRegistry.begin(), kernelNameRegistry.end(),
                     kernelName) != kernelNameRegistry.end();
  }

  static const std::string &registerKernelName(const std::string &kernelName) {
    return kernelNameRegistry.emplace_back(kernelName);
  }

private:
  /// Keeps kernel names created during argument conversion in memory.
  /// References to those names are used by the argument converters for
  /// those kernels.
  /// Note: use std::list to make sure we always return valid references
  /// when registering new kernel names.
  static std::list<std::string> kernelNameRegistry;

  mlir::ModuleOp sourceModule;
  mlir::ModuleOp substModule;
  mlir::OpBuilder builder;
  mlir::StringRef kernelName;
  mlir::SmallVector<cc::ArgumentSubstitutionOp> substitutions;
  std::vector<ArgumentConverter> calleeConverters;
};

} // namespace cudaq::opt
