name: ccache-setup
description: Install ORAS and ccache, configure ccache settings

inputs:
  max-size:
    description: 'Maximum ccache cache size'
    required: false
    default: '3G'
  compression:
    description: 'Enable ccache compression'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install ORAS
      shell: bash
      run: |
        if command -v oras &>/dev/null; then
          echo "ORAS already installed: $(oras version)"
          exit 0
        fi
        oras_version="1.2.2"
        os=$(uname -s | tr '[:upper:]' '[:lower:]')
        arch=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
        curl -sLO "https://github.com/oras-project/oras/releases/download/v${oras_version}/oras_${oras_version}_${os}_${arch}.tar.gz"
        sudo tar -xzf oras_*.tar.gz -C /usr/local/bin/ oras
        rm -f oras_*.tar.gz

    - name: Install and configure ccache
      shell: bash
      run: |
        if ! command -v ccache &>/dev/null; then
          if [ "$(uname)" = "Darwin" ]; then
            brew install ccache
          else
            sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends ccache
          fi
        fi
        ccache --set-config=max_size=${{ inputs.max-size }}
        ccache --set-config=compression=${{ inputs.compression }}
        # Use environment variables for settings that must be visible to all
        # ccache invocations (env vars override config file and avoid issues
        # with config file location resolution).
        {
          echo "CCACHE_DIR=$HOME/.ccache"
          echo "CCACHE_BASEDIR=${GITHUB_WORKSPACE:-$(pwd)}"
          echo "CCACHE_SLOPPINESS=include_file_mtime,include_file_ctime,time_macros,pch_defines"
          echo "CCACHE_COMPILERCHECK=content"
          echo "CCACHE_LOGFILE=${GITHUB_WORKSPACE:-$(pwd)}/ccache.log"
        } >> $GITHUB_ENV
        # Export for the ccache -z call below (GITHUB_ENV only applies to subsequent steps)
        export CCACHE_DIR="$HOME/.ccache"
        ccache -z
