/*******************************************************************************
 * Copyright (c) 2026 NVIDIA Corporation & Affiliates.                         *
 * All rights reserved.                                                        *
 *                                                                             *
 * This source code and the accompanying materials are made available under    *
 * the terms of the Apache License 2.0 which accompanies this distribution.    *
 *******************************************************************************/

#ifndef QLX_PYTHON_QLXATTRS_TD
#define QLX_PYTHON_QLXATTRS_TD

include "qlx/Dialect/QLX/IR/QLXAttrs.td"

#endif // QLX_PYTHON_QLXATTRS_TD
