from __future__ import annotations

from collections.abc import Mapping
from typing import Optional

import numpy as np


def _total_dimension(dimensions: Mapping[int, int]) -> int:
    dimension = 1
    for local_dimension in dimensions.values():
        dimension *= local_dimension
    return dimension


def _identity_state(dimension: int):
    import cudaq

    identity = np.eye(dimension, dtype=np.complex128).reshape(-1)
    return cudaq.State.from_data(identity)


def _state_to_matrix(state, dimension: int) -> np.ndarray:
    data = np.array(state).reshape(-1)
    expected_size = dimension * dimension

    if data.size != expected_size:
        raise RuntimeError(
            "Expected final propagator state with size "
            f"{expected_size}, got {data.size}.")

    return data.reshape((dimension, dimension))


def _generator(hamiltonian):
    import cudaq

    generator = cudaq.SuperOperator()
    generator += cudaq.SuperOperator.left_multiply(-1j * hamiltonian)
    return generator


def propagator(
    hamiltonian,
    dimensions: Mapping[int, int],
    schedule,
    *,
    integrator=None,
    max_batch_size: Optional[int] = None,
):
    """Compute a closed-system dynamics propagator.

    Computes the matrix U satisfying

        dU/dt = -i H(t) U,  U(t_initial) = I,

    by evolving the identity matrix under the left-multiplication
    superoperator generated by ``-i H(t)``.

    Args:
        hamiltonian: CUDA-Q operator H(t).
        dimensions: Mapping from degree-of-freedom index to local dimension.
        schedule: CUDA-Q dynamics schedule.
        integrator: Optional dynamics integrator.
        max_batch_size: Optional maximum batch size for the dynamics backend.

    Returns:
        Dense complex NumPy array with shape ``(dim, dim)``.
    """
    import cudaq

    dimension = _total_dimension(dimensions)

    result = cudaq.evolve(
        _generator(hamiltonian),
        dimensions,
        schedule,
        _identity_state(dimension),
        collapse_operators=[],
        observables=[],
        store_intermediate_results=cudaq.IntermediateResultSave.NONE,
        integrator=integrator,
        max_batch_size=max_batch_size,
    )

    return _state_to_matrix(result.final_state(), dimension)
