from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Optional

import numpy as np


def _total_dimension(dimensions: Mapping[int, int]) -> int:
    dimension = 1
    for local_dimension in dimensions.values():
        dimension *= local_dimension
    return dimension


def _identity_state(dimension: int):
    import cudaq

    identity = np.eye(dimension, dtype=np.complex128).reshape(-1)
    return cudaq.State.from_data(identity)


def _state_to_matrix(state, dimension: int) -> np.ndarray:
    data = np.array(state).reshape(-1)
    expected_size = dimension * dimension

    if data.size != expected_size:
        raise RuntimeError(
            "Expected propagator state with size "
            f"{expected_size}, got {data.size}.")

    return data.reshape((dimension, dimension))


def _generator(hamiltonian):
    import cudaq

    generator = cudaq.SuperOperator()
    generator += cudaq.SuperOperator.left_multiply(-1j * hamiltonian)
    return generator


def _extract_propagator(result, dimension: int,
                        store_intermediate_results: bool):
    if store_intermediate_results:
        return [
            _state_to_matrix(state, dimension)
            for state in result.intermediate_states()
        ]

    return _state_to_matrix(result.final_state(), dimension)


def propagator(
    hamiltonian,
    dimensions: Mapping[int, int],
    schedule,
    *,
    store_intermediate_results: bool = False,
    integrator=None,
    max_batch_size: Optional[int] = None,
):
    """Compute closed-system dynamics propagators.

    Computes the matrix U satisfying

        dU/dt = -i H(t) U,  U(t_initial) = I,

    by evolving the identity matrix under the left-multiplication
    superoperator generated by ``-i H(t)``.

    Args:
        hamiltonian: CUDA-Q operator H(t), or a sequence of operators for
            batched propagator computation.
        dimensions: Mapping from degree-of-freedom index to local dimension.
        schedule: CUDA-Q dynamics schedule.
        store_intermediate_results: If True, return propagators at the
            intermediate schedule points saved by the dynamics backend.
        integrator: Optional dynamics integrator.
        max_batch_size: Optional maximum batch size for the dynamics backend.

    Returns:
        For a single Hamiltonian, returns a dense complex NumPy array with shape
        ``(dim, dim)``. If ``store_intermediate_results`` is True, returns a
        list of dense matrices.

        For a sequence of Hamiltonians, returns one such result per Hamiltonian.
    """
    import cudaq

    dimension = _total_dimension(dimensions)
    is_batched = isinstance(hamiltonian, Sequence)

    hamiltonians = list(hamiltonian) if is_batched else [hamiltonian]
    generators = [_generator(h) for h in hamiltonians]
    initial_states = [_identity_state(dimension) for _ in generators]

    save_mode = (cudaq.IntermediateResultSave.ALL
                 if store_intermediate_results else
                 cudaq.IntermediateResultSave.NONE)

    result = cudaq.evolve(
        generators if is_batched else generators[0],
        dimensions,
        schedule,
        initial_states if is_batched else initial_states[0],
        collapse_operators=[],
        observables=[],
        store_intermediate_results=save_mode,
        integrator=integrator,
        max_batch_size=max_batch_size,
    )

    if is_batched:
        return [
            _extract_propagator(single_result, dimension,
                                store_intermediate_results)
            for single_result in result
        ]

    return _extract_propagator(result, dimension, store_intermediate_results)
