name: start-pypi-server

# This action starts a private PyPI server at localhost from a set of wheel files
# provided as GitHub release assets.

# FIXME: remove this file before merging to public repo

inputs:
  # Github release name where the wheel assets are hosted
  release_name:
    required: true
  # Port of the localhost PyPI server
  port:
    default: 8080
    required: false

outputs:
  local_pypi_server_url:
    description: "Local PyPI server URL"
    value: ${{ steps.start_pypi_server.outputs.local_pypi_server_url }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd /tmp && mkdir pip-packages && cd pip-packages
        echo "Download ${{ inputs.release_name }} assets..."
        gh release download ${{ inputs.release_name }} -R ${{ github.repository }}
      env:
        GH_TOKEN: ${{ github.token }}
    
    - id: start_pypi_server
      shell: bash
      run: |
        docker run --rm -dit -p ${{ inputs.port }}:8080 -v /tmp/pip-packages:/data/packages:rw pypiserver/pypiserver:latest
        echo "local_pypi_server_url=http://localhost:${{ inputs.port }}" >> $GITHUB_OUTPUT