/*******************************************************************************
 * Copyright (c) 2026 NVIDIA Corporation & Affiliates.                         *
 * All rights reserved.                                                        *
 *                                                                             *
 * This source code and the accompanying materials are made available under    *
 * the terms of the Apache License 2.0 which accompanies this distribution.    *
 ******************************************************************************/

#include "PassDetails.h"
#include "cudaq/Optimizer/CodeGen/Passes.h"

namespace cudaq::opt {
#define GEN_PASS_DEF_ERASECOMPILERGENERATEDLOGOUTPUT
#include "cudaq/Optimizer/CodeGen/Passes.h.inc"
} // namespace cudaq::opt

#define DEBUG_TYPE "erase-implicit-output"

using namespace mlir;

namespace {

class EraseCompilerGeneratedLogOutputPass
    : public cudaq::opt::impl::EraseCompilerGeneratedLogOutputBase<
          EraseCompilerGeneratedLogOutputPass> {
public:
  using EraseCompilerGeneratedLogOutputBase::
      EraseCompilerGeneratedLogOutputBase;

  void runOnOperation() override {
    func::FuncOp funcOp = getOperation();
    // Collect first: log_output ops may live in nested regions (e.g. inside a
    // cc.loop body generated by inject-implicit-output for veq allocas), so a
    // simple top-level block scan would miss them.  Collect all candidates with
    // walk(), then erase in a second pass to avoid iterator invalidation.
    SmallVector<cudaq::quake::LogOutputOp> toErase;
    funcOp.walk([&](cudaq::quake::LogOutputOp logOut) {
      if (logOut.getCompilerGenerated())
        toErase.push_back(logOut);
    });
    for (auto logOut : toErase) {
      // For each wire/cable result, replace uses with the corresponding arg.
      unsigned resultIdx = 0;
      for (Value arg : logOut.getArgs())
        if (cudaq::quake::isLinearType(arg.getType()))
          logOut.getOuts()[resultIdx++].replaceAllUsesWith(arg);
      logOut->erase();
    }
    // After erasing the log_output ops, any empty cc.loop bodies left behind
    // (from the veq loop pattern) can be cleaned up by canonicalization; the
    // cc.loop with no side effects will be DCE'd.
  }
};
} // namespace
