[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "testcudaq"
version = "0.0.1"
description = "TODO"
requires-python = ">=3.10"
dependencies = ["numpy", "pytest", "sphinx-toolbox", "pycairo"]


include = [
    {path = "testcudaq/*.so", format = "wheel"}
]
packages = [
    { include = "testcudaq" },
    { include = "testcudaq/_cudaq.cpython-310-x86_64-linux-gno.so" },
]

[tool.setuptools.package-data]
testcudaq = ["./testcudaq/_cudaq.cpython-310-x86_64-linux-gno.so"]