name: install-ngc-cli

inputs:
  version:
    required: true
  checksum:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends wget
        wget -O ngccli_linux.zip --content-disposition \
          https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/${{ inputs.version }}/files/ngccli_linux.zip
        if [ -z "$(sha256sum ngccli_linux.zip | grep -o '${{ inputs.checksum }} ')" ]; then
          echo "::error::NGC CLI was corrupted during download." && exit 1
        fi
        unzip ngccli_linux.zip && chmod u+x ngc-cli/ngc
