name: ccache-push
description: Push ccache data to GHCR via ORAS

inputs:
  cache-key:
    description: 'Tag prefix for the ccache artifact, e.g. arm64-build, amd64-devenv'
    required: true
  cache-path:
    description: 'Path to the ccache data directory to push (e.g. ~/.ccache)'
    required: true
  registry-token:
    description: 'GitHub token for GHCR authentication'
    required: true
  pr-number:
    description: 'PR number for tag. Auto-detected from ref_name when empty.'
    required: false
    default: ''
  miss-threshold:
    description: 'Skip push if ccache miss rate is below this percentage. Set to 0 to always push.'
    required: false
    default: '10'
  ref-name:
    description: 'Branch name used for tag when not a PR build'
    required: false
    default: ${{ github.ref_name }}
  upload-log:
    description: 'Upload the ccache log file as a short-lived artifact for debugging'
    required: false
    default: 'false'

outputs:
  pushed:
    description: 'Whether the ccache artifact was pushed'
    value: ${{ steps.push.outputs.pushed }}

runs:
  using: "composite"
  steps:
    - name: Push ccache to GHCR
      id: push
      continue-on-error: true
      shell: bash
      run: |
        cache_path="${{ inputs.cache-path }}"
        miss_threshold="${{ inputs.miss-threshold }}"

        # Validate cache path has content
        if [ ! -d "$cache_path" ] || [ -z "$(ls -A "$cache_path" 2>/dev/null)" ]; then
          echo "No ccache data found at $cache_path; skipping push."
          echo "pushed=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Collect stats: prefer _build_stats.txt from Docker export,
        # fall back to querying ccache on the host (native builds).
        stats_file="$cache_path/_build_stats.txt"
        if [ -f "$stats_file" ]; then
          echo "=== ccache stats (from Docker build) ==="
          cat "$stats_file"
          stats=$(cat "$stats_file")
        elif command -v ccache &>/dev/null; then
          echo "=== ccache stats ==="
          ccache -s 2>/dev/null || true
          stats=$(ccache --print-stats 2>/dev/null || true)
        else
          stats=""
        fi

        # Parse miss/hit counts from --print-stats (tab-separated) or -s output
        if [ -n "$stats" ]; then
          cache_miss=$(echo "$stats" | awk -F'\t' '$1=="cache_miss"{print $2}')
          if [ -n "$cache_miss" ]; then
            direct_hit=$(echo "$stats" | awk -F'\t' '$1=="direct_cache_hit"{print $2}')
            preproc_hit=$(echo "$stats" | awk -F'\t' '$1=="preprocessed_cache_hit"{print $2}')
            cache_hit=$((${direct_hit:-0} + ${preproc_hit:-0}))
          else
            cache_miss=$(echo "$stats" | grep "cache miss" | grep -o '[0-9]*' | head -1)
            cache_hit=$(echo "$stats" | grep "cache hit" | grep -o '[0-9]*' | head -1)
          fi
        fi

        total=$((${cache_hit:-0} + ${cache_miss:-0}))
        if [ "$total" -gt 0 ]; then
          miss_pct=$((cache_miss * 100 / total))
          echo "ccache miss rate: ${miss_pct}% ($cache_miss misses / $total total)"
        fi

        # Always push on the default branch to keep the baseline fresh
        default_branch="${{ github.event.repository.default_branch }}"
        default_branch="${default_branch:-main}"
        is_default_branch=$( [ "${{ github.ref_name }}" = "$default_branch" ] && echo true || echo false )

        if $is_default_branch; then
          echo "On default branch ($default_branch); always pushing to keep baseline fresh."
        elif [ "$miss_threshold" -gt 0 ] 2>/dev/null; then
          if [ "$total" -eq 0 ]; then
            echo "No compilations detected; skipping push."
            echo "pushed=false" >> $GITHUB_OUTPUT
            exit 0
          elif [ "$miss_pct" -lt "$miss_threshold" ]; then
            echo "Miss rate below ${miss_threshold}%; skipping push."
            echo "pushed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi

        # Extract log and stats from cache dir before tarring so they
        # don't bloat the GHCR artifact. The log is placed where the
        # upload-artifact step expects it.
        if [ -f "$cache_path/ccache.log" ]; then
          mv "$cache_path/ccache.log" "${GITHUB_WORKSPACE:-$(pwd)}/ccache.log"
        fi
        rm -f "$stats_file"

        # Determine tag
        repo_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        platform=$([ "$(uname)" = "Darwin" ] && echo macos || echo linux)
        image="ghcr.io/${repo_owner}/cuda-quantum-${platform}-ccache"
        cache_key="${{ inputs.cache-key }}"

        # Auto-detect PR number from ref name if not provided
        pr_number="${{ inputs.pr-number }}"
        if [ -z "$pr_number" ]; then
          pr_number=$(echo "${{ github.ref_name }}" | grep pull-request/ | grep -o '[0-9]*' || true)
          pr_number=${pr_number:-${{ github.event.pull_request.number }}}
        fi

        if [ -n "$pr_number" ]; then
          tag="${cache_key}-pr-${pr_number}"
        else
          tag="${cache_key}-${{ inputs.ref-name }}"
        fi

        # Tar the contents of the cache directory (not the directory itself)
        tar -czf ccache-data.tar.gz -C "$cache_path" .
        echo "ccache tarball size: $(du -sh ccache-data.tar.gz | cut -f1) (uncompressed: $(du -sh "$cache_path" | cut -f1))"
        echo "${{ inputs.registry-token }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin
        oras push "$image:$tag" ccache-data.tar.gz
        rm -f ccache-data.tar.gz
        echo "Pushed ccache to $image:$tag"
        echo "pushed=true" >> $GITHUB_OUTPUT

    - name: Generate unique artifact name
      if: always() && inputs.upload-log == 'true'
      id: artifact
      shell: bash
      run: echo "name=ccache-log-${{ inputs.cache-key }}-$RANDOM" >> $GITHUB_OUTPUT

    - name: Upload ccache log
      if: always() && inputs.upload-log == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact.outputs.name }}
        path: ${{ github.workspace }}/ccache.log
        retention-days: 1
        if-no-files-found: ignore
