/*******************************************************************************
 * Copyright (c) 2022 - 2026 NVIDIA Corporation & Affiliates.                  *
 * All rights reserved.                                                        *
 *                                                                             *
 * This source code and the accompanying materials are made available under    *
 * the terms of the Apache License 2.0 which accompanies this distribution.    *
 ******************************************************************************/

// An explicitly empty `__qpu__` helper kernel must still be emitted as a gate
// definition so that call sites in the entry point remain valid.

// RUN: cudaq-quake %s | cudaq-translate --convert-to=openqasm2 | FileCheck %s

#include <cudaq.h>

struct noop {
  void operator()(cudaq::qubit &q) __qpu__ {}
};

struct caller {
  void operator()() __qpu__ {
    cudaq::qvector q(1);
    noop{}(q[0]);
    mz(q);
  }
};

int main() { cudaq::sample(caller{}); }

// CHECK:  // Code generated by NVIDIA's nvq++ compiler
// CHECK:  OPENQASM 2.0;

// CHECK:  include "qelib1.inc";

// CHECK:  gate nvqpp__mlirgen__noop q0 {
// CHECK:  }

// CHECK:  qreg var0[1];
// CHECK:  nvqpp__mlirgen__noop var0[0];
// CHECK:  creg var2[1];
// CHECK:  measure var0 -> var2[0];
