/*******************************************************************************
 * Copyright (c) 2022 - 2024 NVIDIA Corporation & Affiliates.                  *
 * All rights reserved.                                                        *
 *                                                                             *
 * This source code and the accompanying materials are made available under    *
 * the terms of the Apache License 2.0 which accompanies this distribution.    *
 ******************************************************************************/

// RUN: cudaq-quake  %s | cudaq-translate --convert-to=openqasm2 | FileCheck %s

#include <cudaq.h>

CUDAQ_REGISTER_OPERATION(custom_h, 1, 0,
                         {M_SQRT1_2, M_SQRT1_2, M_SQRT1_2, -M_SQRT1_2})

CUDAQ_REGISTER_OPERATION(custom_cnot, 2, 0,
                         {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0})

__qpu__ void bell_pair() {
  cudaq::qubit q, r;
  custom_h(q);
  custom_cnot(q, r);
}

// CHECK:  // Code generated by NVIDIA's nvq++ compiler
// CHECK:  OPENQASM 2.0;

// CHECK:  include "qelib1.inc";

// CHECK:  gate Z9bell_pairv  {
// CHECK:  }

// CHECK:  qreg var0[1];
// CHECK:  qreg var1[1];
// CHECK:  rz(3.141593e+00) var0[0];
// CHECK:  ry(1.570796e+00) var0[0];
// CHECK:  u1(3.141593e+00) var0[0];
// CHECK:  rz(-3.141593e+00) var0[0];
// CHECK:  ry(1.570796e+00) var1[0];
// CHECK:  rz(2.725460e+00) var1[0];
// CHECK:  rz(-3.406437e+00) var0[0];
// CHECK:  rz(3.999978e-01) var0[0];
// CHECK:  rx(1.570796e+00) var0[0];
// CHECK:  rx(1.570796e+00) var1[0];
// CHECK:  cx var1[0], var0[0];
// CHECK:  rz(-3.141593e+00) var0[0];
// CHECK:  cx var1[0], var0[0];
// CHECK:  rx(-1.570796e+00) var1[0];
// CHECK:  rx(-1.570796e+00) var0[0];
// CHECK:  cx var1[0], var0[0];
// CHECK:  rz(-1.570796e+00) var0[0];
// CHECK:  cx var1[0], var0[0];
// CHECK:  rz(1.154664e+00) var1[0];
// CHECK:  ry(1.570796e+00) var1[0];
// CHECK:  rz(1.893954e+00) var0[0];
// CHECK:  ry(3.141593e+00) var0[0];
// CHECK:  rz(3.329597e+00) var0[0];
// CHECK:  u1(1.570796e+00) var0[0];
// CHECK:  rz(-1.570796e+00) var0[0];