on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

name: "CLA bot"

jobs:
  cla-acknowledgement:
    runs-on: ubuntu-latest
    name: "Check that the CLA has been acknowledged"
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the Contributor License Agreement and I hereby accept the Terms.') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
        with:
          remote-organization-name: NVIDIA
          remote-repository-name: cuda-quantum
          branch: 'bot/data'
          path-to-signatures: 'cla.json'
          custom-allsigned-prcomment: 'All Contributors have signed the CLA.'
          custom-pr-sign-comment: 'I have read the Contributor License Agreement and I hereby accept the Terms.'
          allowlist: user1,bot*
          # edit the path below (if needed) to point to the document containing the CLA that a contributor agrees to
          path-to-document: 'https://github.com/NVIDIA/cuda-quantum/blob/main/Contributor_License_Agreement.md' 