name: Build and Test Framework
on: [push]
jobs:
  build-and-test-osx:
    name: Build and Test Cuda Quantum - OSX 
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3'
      - shell: bash -exl {0}
        run: |
          brew install --cask miniconda
          conda init zsh
          source ~/.zshrc
          conda env create -f conda/environment_cuda_quantum_osx.yml --name cuda-quantum
          conda activate cuda-quantum
          # error: default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default] - patch this
          git -c submodule.tpls/llvm.update=none submodule update --init --recursive
          mv scripts/patch_googletest_v1.12.0.txt tpls/googletest-src
          cd tpls/googletest-src
          git apply patch_googletest_v1.12.0.txt
          cd -
          mkdir -p build && cd build
          bash ../scripts/build_and_run.sh
  build-and-test-linux:
    name: Build and Test Cuda Quantum - Linux 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*" 
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: cuda-quantum 
          environment-file: conda/environment_cuda_quantum_gcc.yml 
      - shell: bash -exl {0} 
        run: |
          sudo apt-get purge '^clang.*' '^llvm.*' '^cmake.*'
          git -c submodule.tpls/llvm.update=none submodule update --init --recursive
          mkdir -p build && cd build
          bash ../scripts/build_and_run.sh
