on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      full_image_name:
        required: true
        type: string
    outputs:
      devdeps:
        description: "A tar file containing the dev environment image"
        value: ${{ jobs.load_devenv.outputs.devdeps }}

name: Load or build the dev environment image

env:
  default_cache_name: cuda-quantum-devdeps-${{ inputs.toolchain }}
  cache_name: ${{ github.ref_name  }}-cuda-quantum-devdeps-${{ inputs.toolchain }}

jobs:
  load_devenv:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up buildx runner
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for dev environment
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.full_image_name }}
          flavor: |
            latest=true
            prefix=${{ inputs.toolchain }}-,onlatest=true
          tags: |
            # workflow dispatch is covered by these
            type=schedule,enable=true,pattern=nightly
            type=ref,enable=true,event=branch
            type=ref,enable=true,prefix=${{ inputs.toolchain }}-pr-,event=pr
            type=ref,enable=true,event=tag

      - name: Build dev environment image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/build/devenv.Dockerfile
          build-args: |
              toolchain=${{ inputs.toolchain }}
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          cache-from: |
            type=gha,scope=${{ env.cache_name }}
            type=gha,scope=${{ env.default_cache_name }}
          cache-to: |
            type=gha,mode=max,scope=${{ env.cache_name }}
          outputs: 
            devdeps: type=docker,dest=/tmp/devdeps.tar
