on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'releases/*'
    types:
      - closed

name: Publish dev environment image and update cache

env:
  cache_name: cuda-quantum-devdeps-${{ inputs.toolchain }}

jobs:
  update-devenv-cache:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/load_devenv.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      cache_name: ${{ env.cache_name }}
      full_image_name: ${{ env.registry }}/${{ env.image_name }}

  push-devenv-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step pushes the image to the GitHub container registry.
      - name: Push dev environment image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/build/devenv.Dockerfile
          build-args: |
              toolchain=${{ env.TOOLCHAIN }}
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          cache-from: |
            type=gha,scope=${{ env.cache_name }}
          outputs: type=docker,dest=/tmp/devdeps.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.cache_name }}
          path: /tmp/devdeps.tar