on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/*'

name: Push dev images and update caches

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: true

jobs:
  devdeps_gcc11:
    uses: ./.github/workflows/dev_environment.yml
    with:
      toolchain: gcc11
      cache_location: ${{ github.event.pull_request.base.ref }}
      container_registry: ghcr.io

  devdeps_clang15:
    uses: ./.github/workflows/dev_environment.yml
    with:
      toolchain: clang15
      cache_location: ${{ github.event.pull_request.base.ref }}
      container_registry: ghcr.io
