
name: test

defaults:
  run:
    shell: bash -euo pipefail {0}

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: linux-arm64-cpu4
    steps:
      - name: Test echo
        run: |
        echo "Hello"
        uname -m