on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

name: Update dev environment image and cache

env:
  cache_name: cuda-quantum-devdeps-${{ inputs.toolchain }}

jobs:
  update_devenv_cache:
    uses: ./.github/workflows/load_devenv.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      cache_name: ${{ env.cache_name }}
      full_image_name: ${{ env.registry }}/${{ env.image_name }}

  push_devenv_image:
    needs: update_devenv_cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step pushes the image to the GitHub container registry.
      - name: Push dev environment image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/build/devenv.Dockerfile
          build-args: |
              toolchain=${{ inputs.toolchain }}
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          cache-from: |
            type=gha,scope=${{ env.cache_name }}
          outputs: type=docker,dest=/tmp/devdeps.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.cache_name }}
          path: /tmp/devdeps.tar